services:
  api: 
    build: .
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro #ro = read only
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=13579
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30 
    depends_on:
      postgres: # if postgres not healthy, api will not start
        condition: service_healthy

  postgres:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=13579
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5


volumes:
  postgres-db:
